In [1]:
import numpy as np

In [2]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a = np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [4]:
a = np.arange(5*3).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [5]:
a = np.arange(4*3*10*10).reshape(4,3,10,10)
a

array([[[[   0,    1,    2, ...,    7,    8,    9],
         [  10,   11,   12, ...,   17,   18,   19],
         [  20,   21,   22, ...,   27,   28,   29],
         ...,
         [  70,   71,   72, ...,   77,   78,   79],
         [  80,   81,   82, ...,   87,   88,   89],
         [  90,   91,   92, ...,   97,   98,   99]],

        [[ 100,  101,  102, ...,  107,  108,  109],
         [ 110,  111,  112, ...,  117,  118,  119],
         [ 120,  121,  122, ...,  127,  128,  129],
         ...,
         [ 170,  171,  172, ...,  177,  178,  179],
         [ 180,  181,  182, ...,  187,  188,  189],
         [ 190,  191,  192, ...,  197,  198,  199]],

        [[ 200,  201,  202, ...,  207,  208,  209],
         [ 210,  211,  212, ...,  217,  218,  219],
         [ 220,  221,  222, ...,  227,  228,  229],
         ...,
         [ 270,  271,  272, ...,  277,  278,  279],
         [ 280,  281,  282, ...,  287,  288,  289],
         [ 290,  291,  292, ...,  297,  298,  299]]],


       [[[ 300

In [6]:
#                              s,r,c
#slide=s
a = np.arange(3*10*10).reshape(3,10,10)
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [11]:
a = np.arange(3*10*10).reshape(3,10,10)
a

array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
        [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165,

In [12]:
a = np.arange(3*10*10).reshape(3,10,10)
a[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [13]:
a = np.arange(3*10*10).reshape(3,10,10)
a[1]

array([[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169],
       [170, 171, 172, 173, 174, 175, 176, 177, 178, 179],
       [180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
       [190, 191, 192, 193, 194, 195, 196, 197, 198, 199]])

In [14]:
a = np.arange(3*10*10).reshape(3,10,10)
a[2]

array([[200, 201, 202, 203, 204, 205, 206, 207, 208, 209],
       [210, 211, 212, 213, 214, 215, 216, 217, 218, 219],
       [220, 221, 222, 223, 224, 225, 226, 227, 228, 229],
       [230, 231, 232, 233, 234, 235, 236, 237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249],
       [250, 251, 252, 253, 254, 255, 256, 257, 258, 259],
       [260, 261, 262, 263, 264, 265, 266, 267, 268, 269],
       [270, 271, 272, 273, 274, 275, 276, 277, 278, 279],
       [280, 281, 282, 283, 284, 285, 286, 287, 288, 289],
       [290, 291, 292, 293, 294, 295, 296, 297, 298, 299]])

In [15]:
a = np.arange(3*10*10).reshape(3,10,10)
a[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [17]:
a = np.arange(5*3*10*10).reshape(5,3,10,10)
a

array([[[[   0,    1,    2, ...,    7,    8,    9],
         [  10,   11,   12, ...,   17,   18,   19],
         [  20,   21,   22, ...,   27,   28,   29],
         ...,
         [  70,   71,   72, ...,   77,   78,   79],
         [  80,   81,   82, ...,   87,   88,   89],
         [  90,   91,   92, ...,   97,   98,   99]],

        [[ 100,  101,  102, ...,  107,  108,  109],
         [ 110,  111,  112, ...,  117,  118,  119],
         [ 120,  121,  122, ...,  127,  128,  129],
         ...,
         [ 170,  171,  172, ...,  177,  178,  179],
         [ 180,  181,  182, ...,  187,  188,  189],
         [ 190,  191,  192, ...,  197,  198,  199]],

        [[ 200,  201,  202, ...,  207,  208,  209],
         [ 210,  211,  212, ...,  217,  218,  219],
         [ 220,  221,  222, ...,  227,  228,  229],
         ...,
         [ 270,  271,  272, ...,  277,  278,  279],
         [ 280,  281,  282, ...,  287,  288,  289],
         [ 290,  291,  292, ...,  297,  298,  299]]],


       [[[ 300

In [24]:
a[0][0][0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
a[1]

array([[[300, 301, 302, 303, 304, 305, 306, 307, 308, 309],
        [310, 311, 312, 313, 314, 315, 316, 317, 318, 319],
        [320, 321, 322, 323, 324, 325, 326, 327, 328, 329],
        [330, 331, 332, 333, 334, 335, 336, 337, 338, 339],
        [340, 341, 342, 343, 344, 345, 346, 347, 348, 349],
        [350, 351, 352, 353, 354, 355, 356, 357, 358, 359],
        [360, 361, 362, 363, 364, 365, 366, 367, 368, 369],
        [370, 371, 372, 373, 374, 375, 376, 377, 378, 379],
        [380, 381, 382, 383, 384, 385, 386, 387, 388, 389],
        [390, 391, 392, 393, 394, 395, 396, 397, 398, 399]],

       [[400, 401, 402, 403, 404, 405, 406, 407, 408, 409],
        [410, 411, 412, 413, 414, 415, 416, 417, 418, 419],
        [420, 421, 422, 423, 424, 425, 426, 427, 428, 429],
        [430, 431, 432, 433, 434, 435, 436, 437, 438, 439],
        [440, 441, 442, 443, 444, 445, 446, 447, 448, 449],
        [450, 451, 452, 453, 454, 455, 456, 457, 458, 459],
        [460, 461, 462, 463, 464, 465,

In [32]:
np.linspace(0, 2, 7)  

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        ])

In [34]:
a = np.arange(2*2).reshape(2,2)
print(a)

b = np.arange(2*2).reshape(2,2) + 5
print(b)

[[0 1]
 [2 3]]
[[5 6]
 [7 8]]


In [ ]:
[0 1]     [5 5]      [5 6]
       +         =
[2 3]     [5 5]      [7  8]

In [36]:
a = np.array([[0, 1],
              [2 ,3]])
a

array([[0, 1],
       [2, 3]])

In [40]:
a = np.array([[0, 1],
              [2 ,3]])
b = a + 5
print(a)
print(b)

a * b

[[0 1]
 [2 3]]
[[5 6]
 [7 8]]


array([[ 0,  6],
       [14, 24]])

In [41]:
a = np.array([[0, 1],
              [2 ,3]])
b = a + 5
print(a)
print(b)

a @ b

[[0 1]
 [2 3]]
[[5 6]
 [7 8]]


array([[ 7,  8],
       [31, 36]])

In [52]:
np.all([True,True,True]) # and operator

True

In [43]:
np.all([True,False,True])

False

In [44]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
a > 0

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [46]:
np.all(a > 0)

False

In [47]:
np.any(a > 0)

True

In [55]:
#          0 1 2 3  4   
np.argmax([1,7,2,20,3])# max value index


3

In [57]:
np.max([1,7,2,20,3])# value

20

In [58]:
#           0 1 2 3  4
np.argsort([1,7,2,20,3])

array([0, 2, 4, 1, 3])

In [59]:
 #A    B   C   D
[0.2,0.1,0.2,0.5]

print(np.argmax([0.2,0.1,0.2,0.5]))

3


### np.fromfunction

In [70]:
def f(x, y):
    print("x",x)
    print("y",y)
    return x + y

b = np.fromfunction(f, (5, 4), dtype=int)
b

x [[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
y [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

# Shallow Copy

In [74]:
a = np.array([1,2,3])
b = a # nickname
c = b # nickname

print(a)
print(b)
print(c)

[1 2 3]
[1 2 3]
[1 2 3]


In [75]:
c[0] = 20# 
print(a)
print(b)
print(c)

[20  2  3]
[20  2  3]
[20  2  3]


## Deep copy

In [73]:
a = np.array([1,2,3])
b = a.copy()
c = b.copy()

a[0] = 20# 
print(a)
print(b)
print(c)

[20  2  3]
[1 2 3]
[1 2 3]
