In [1]:
import numpy as np # numerical computation
import pandas as pd # structure and textual(re)
import matplotlib.pyplot as plt # data visualization (low level library)
import seaborn as sns # data visualization-> above package on matplotlib, user fiendly

In [5]:
a1 = np.array([chr(i) for i in range(65,93)], dtype=str)
print(a1.dtype)
a1

<U1


array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', '\\'], dtype='<U1')

In [6]:
bank_database = a1
bank_database

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', '\\'], dtype='<U1')

In [12]:
state_bank_data = np.array(['R','RS','A','Z','A'])

In [13]:
np.in1d(state_bank_data, bank_database)

array([ True, False,  True,  True,  True])

In [14]:
np.intersect1d?

In [15]:
np.intersect1d(state_bank_data, bank_database)

array(['A', 'R', 'Z'], dtype='<U2')

In [18]:
state_bank_data = np.array(['R','RS','A','Z','A','c','d','e'])

np.intersect1d(state_bank_data, bank_database)

array(['A', 'R', 'Z'], dtype='<U2')

In [28]:
state_bank_data = np.array(['R','RS','A','Z','A','c','d','e'])
state_bank_data =np.array(list(map(str.lower, state_bank_data)))
state_bank_data

array(['r', 'rs', 'a', 'z', 'a', 'c', 'd', 'e'], dtype='<U2')

In [29]:

bank_database =np.array(list(map(str.lower, bank_database)))
bank_database

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
       '[', '\\'], dtype='<U1')

In [30]:
np.intersect1d(state_bank_data, bank_database)

array(['a', 'c', 'd', 'e', 'r', 'z'], dtype='<U2')

In [31]:
state_bank_data = np.array(['R ','RS','A','Z',' A','c','d    ','e   '])
state_bank_data = np.array(list(map(str.lower, state_bank_data)))
state_bank_data

array(['r ', 'rs', 'a', 'z', ' a', 'c', 'd    ', 'e   '], dtype='<U5')

In [32]:
np.intersect1d(state_bank_data, bank_database)

array(['a', 'c', 'z'], dtype='<U5')

# handle issue like space, lower and uper case with function

In [38]:
def pre_processing(txt):
    return str(txt).lower().strip()


'pakistan zida bad!'

In [46]:
state_bank_data = np.array(['R ','RS','A','Z',' A','c','d    ','e   '])
state_bank_data = np.array(list(map(pre_processing, state_bank_data)))# pass our own function
state_bank_data

array(['r', 'rs', 'a', 'z', 'a', 'c', 'd', 'e'], dtype='<U2')

In [47]:
np.intersect1d(state_bank_data, bank_database)

array(['a', 'c', 'd', 'e', 'r', 'z'], dtype='<U2')

# Slicing and Indexing

In [55]:
bank_database = np.array(['a', 'b' ,'c' ,'d' ,'e' ,'f', 'g' ,'h' ])
bank_database

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='<U1')

In [57]:
bank_database = np.array(['a', 'b' ,'c' ,'d' ,'e' ,'f', 'g' ,'h' ])

print(bank_database)

print(bank_database[0])# 0 index  'a'


['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h']
a


In [59]:
# -->                      0    1    2    3    4    5    6    7   
bank_database = np.array(['a', 'b' ,'c' ,'d' ,'e' ,'f', 'g' ,'h' ])
# <--                                                -3, -2  -1

print(bank_database)

print(bank_database[0])# 0 index  'a'


['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h']
a


In [58]:
# -->                      0    1    2    3    4    5    6    7   
bank_database = np.array(['a', 'b' ,'c' ,'d' ,'e' ,'f', 'g' ,'h' ])
# <--                                                -3, -2  -1

print(bank_database)

print(bank_database[-8])# 0 index  'a'

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h']
a


# Slicing

In [62]:
# -->                      0    1    2    3    4    5    6    7   
bank_database = np.array(['a', 'b' ,'c' ,'d' ,'e' ,'f', 'g' ,'h' ])
# <--                                                -3, -2  -1


# variable_name[start:end:step] 
# start include (indexing)
# end exclude or end-1 indexing
# step defualt 1
print(bank_database[2:6])
print(bank_database[2:6:])
print(bank_database[2:6:1])

['c' 'd' 'e' 'f']
['c' 'd' 'e' 'f']
['c' 'd' 'e' 'f']


In [63]:
a = bank_database[2:6:]
a

array(['c', 'd', 'e', 'f'], dtype='<U1')

In [67]:
# -->                      0    1    2    3    4    5    6    7   
bank_database = np.array(['a', 'b' ,'c' ,'d' ,'e' ,'f', 'g' ,'h' ])
# <--                                                -3, -2  -1


# variable_name[start:end:step] 
# start include (indexing)
# end exclude or end-1 indexing
# step defualt 1
# if we dont write any above three arguments then it include defualt value
print(bank_database[2])#index
print(bank_database[2:])
print(bank_database[2::])
print(bank_database[-3:])



c
['c' 'd' 'e' 'f' 'g' 'h']
['c' 'd' 'e' 'f' 'g' 'h']
['f' 'g' 'h']


In [69]:
# -->                      0    1    2    3    4    5    6    7   
bank_database = np.array(['a', 'b' ,'c' ,'d' ,'e' ,'f', 'g' ,'h' ])
# <--                                                -3, -2  -1


# variable_name[start:end:step] 
# start include (indexing)
# end exclude or end-1 indexing
# step defualt 1
# if we dont write any above three arguments then it include defualt value
print(bank_database[::-1])#index
print(bank_database[2::-1])#index



['h' 'g' 'f' 'e' 'd' 'c' 'b' 'a']
['c' 'b' 'a']


# Boolean Indexing

In [70]:
bank_database = np.array(['a', 'b' ,'c' ,'d' ,'e' ,'f', 'g' ,'h' ])
# we have to pass same array length items array with boolean values
# it only take True index item
bool_list = [True,True,True,True,True,True,True,True]# lenght should be same, list
bank_database[bool_list]

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='<U1')

In [74]:
bank_database = np.array(['a', 'b' ,'c' ,'d' ,'e' ,'f', 'g' ,'h' ])
# we have to pass same array length items array with boolean values
# it only take True index item
bool_list = [True,False,True,False,False,False,True,False]# lenght should be same, list
bank_database[bool_list]

array(['a', 'c', 'g'], dtype='<U1')

In [75]:
np.in1d(['a','b','g','z'], bank_database)

array([ True,  True,  True, False])

In [81]:
bool_list = np.in1d( ['a','b','g','z'],bank_database)
bool_list

array([ True,  True,  True, False])

In [82]:
bank_database[bool_list]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 8 but corresponding boolean dimension is 4

In [79]:
bool_list = np.in1d(bank_database, ['a','b','g','z'])
bool_list

array([ True,  True, False, False, False, False,  True, False])

In [80]:
bank_database[bool_list]

array(['a', 'b', 'g'], dtype='<U1')

# apply boolean slicing with coditional base operator on numeric values

In [84]:
a = np.arange(1,1001)
a

array([   1,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
         23,   24,   25,   26,   27,   28,   29,   30,   31,   32,   33,
         34,   35,   36,   37,   38,   39,   40,   41,   42,   43,   44,
         45,   46,   47,   48,   49,   50,   51,   52,   53,   54,   55,
         56,   57,   58,   59,   60,   61,   62,   63,   64,   65,   66,
         67,   68,   69,   70,   71,   72,   73,   74,   75,   76,   77,
         78,   79,   80,   81,   82,   83,   84,   85,   86,   87,   88,
         89,   90,   91,   92,   93,   94,   95,   96,   97,   98,   99,
        100,  101,  102,  103,  104,  105,  106,  107,  108,  109,  110,
        111,  112,  113,  114,  115,  116,  117,  118,  119,  120,  121,
        122,  123,  124,  125,  126,  127,  128,  129,  130,  131,  132,
        133,  134,  135,  136,  137,  138,  139,  140,  141,  142,  143,
        144,  145,  146,  147,  148,  149,  150,  1

In [88]:
a % 5

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2,
       3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4,
       0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3,
       4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0,
       1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2,
       3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4,
       0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3,
       4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0,
       1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2,
       3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4,
       0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
       2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,

In [90]:
a % 5 == 0

array([False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False,  True,
       False, False, False, False,  True, False, False, False, False,
        True, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False, False,  True, False, False,
       False, False,  True, False, False, False, False,  True, False,
       False, False,

In [91]:
a[(a % 5 == 0)]

array([   5,   10,   15,   20,   25,   30,   35,   40,   45,   50,   55,
         60,   65,   70,   75,   80,   85,   90,   95,  100,  105,  110,
        115,  120,  125,  130,  135,  140,  145,  150,  155,  160,  165,
        170,  175,  180,  185,  190,  195,  200,  205,  210,  215,  220,
        225,  230,  235,  240,  245,  250,  255,  260,  265,  270,  275,
        280,  285,  290,  295,  300,  305,  310,  315,  320,  325,  330,
        335,  340,  345,  350,  355,  360,  365,  370,  375,  380,  385,
        390,  395,  400,  405,  410,  415,  420,  425,  430,  435,  440,
        445,  450,  455,  460,  465,  470,  475,  480,  485,  490,  495,
        500,  505,  510,  515,  520,  525,  530,  535,  540,  545,  550,
        555,  560,  565,  570,  575,  580,  585,  590,  595,  600,  605,
        610,  615,  620,  625,  630,  635,  640,  645,  650,  655,  660,
        665,  670,  675,  680,  685,  690,  695,  700,  705,  710,  715,
        720,  725,  730,  735,  740,  745,  750,  7

In [99]:
~(a % 5 == 0)

array([ True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,

In [100]:
a[~(a % 5 == 0)]

array([  1,   2,   3,   4,   6,   7,   8,   9,  11,  12,  13,  14,  16,
        17,  18,  19,  21,  22,  23,  24,  26,  27,  28,  29,  31,  32,
        33,  34,  36,  37,  38,  39,  41,  42,  43,  44,  46,  47,  48,
        49,  51,  52,  53,  54,  56,  57,  58,  59,  61,  62,  63,  64,
        66,  67,  68,  69,  71,  72,  73,  74,  76,  77,  78,  79,  81,
        82,  83,  84,  86,  87,  88,  89,  91,  92,  93,  94,  96,  97,
        98,  99, 101, 102, 103, 104, 106, 107, 108, 109, 111, 112, 113,
       114, 116, 117, 118, 119, 121, 122, 123, 124, 126, 127, 128, 129,
       131, 132, 133, 134, 136, 137, 138, 139, 141, 142, 143, 144, 146,
       147, 148, 149, 151, 152, 153, 154, 156, 157, 158, 159, 161, 162,
       163, 164, 166, 167, 168, 169, 171, 172, 173, 174, 176, 177, 178,
       179, 181, 182, 183, 184, 186, 187, 188, 189, 191, 192, 193, 194,
       196, 197, 198, 199, 201, 202, 203, 204, 206, 207, 208, 209, 211,
       212, 213, 214, 216, 217, 218, 219, 221, 222, 223, 224, 22

In [102]:
(a % 5 == 0) & (a % 30 == 0)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
       False, False,

In [103]:
a[(a % 5 == 0) & (a % 30 == 0)]

array([ 30,  60,  90, 120, 150, 180, 210, 240, 270, 300, 330, 360, 390,
       420, 450, 480, 510, 540, 570, 600, 630, 660, 690, 720, 750, 780,
       810, 840, 870, 900, 930, 960, 990])

### Fancy Slicing

In [109]:
a = np.array(['a','b','c','d','e'])
# pass list with your own select index which you whant/ list can be with any length
list1 = [0]

a[list1]

array(['a'], dtype='<U1')

In [110]:
a = np.array(['a','b','c','d','e'])
# pass list with your own select index which you whant/ list can be with any length
list1 = [0,1]

a[list1]

array(['a', 'b'], dtype='<U1')

In [111]:
a = np.array(['a','b','c','d','e'])
# pass list with your own select index which you whant/ list can be with any length
list1 = [0,1,3]

a[list1]

array(['a', 'b', 'd'], dtype='<U1')

In [112]:
a = np.array(['a','b','c','d','e'])
# pass list with your own select index which you whant/ list can be with any length
list1 = [0,1,3,-1]

a[list1]

array(['a', 'b', 'd', 'e'], dtype='<U1')

In [113]:
a = np.array(['a','b','c','d','e'])
# pass list with your own select index which you whant/ list can be with any length
list1 = [0,1,3,-1,0,0,0,0,0]# list of indexes

a[list1]

array(['a', 'b', 'd', 'e', 'a', 'a', 'a', 'a', 'a'], dtype='<U1')